apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default   # <-- must match the Fargate profile selector namespace
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
