apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default   # <-- must match the Fargate profile selector namespace
  labels:
    app: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
