apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default   # <-- must match the Fargate profile selector namespace
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend
          ports:
            - containerPort: 3000
