apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: LoadBalancer  # Service type LoadBalancer creates an external load balancer (in supported environments/clouds).
                      # If not explicitly defined in Terraform, Kubernetes will provision the LoadBalancer automatically.
  selector:
    app: frontend
  ports:
    - protocol: TCP
      nodePort: 30008 # Port on the node to expose to load balancer. Security group of node must accept traffic on that port from load balancer.
      port: 80 # NodePort forwards to Service port 80. The Service listens on port 80 (for clients inside the cluster brought by load balancer).
      targetPort: 3000 # Port the pod container listens on. Service forwards traffic to port 3000.
