apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default   # <-- must match the Fargate profile selector namespace
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
