name: Backend CI

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  lint:
    name: Lint Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Check python version
        run: python --version

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Lint
        run: pipenv run lint 

  test:
    name: Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests
        run: pipenv run test 

  build:
    name: Build Docker Image
    needs: [lint, test]
    env:
      REPO_URL: 576165291816.dkr.ecr.eu-central-1.amazonaws.com
      IMAGE_NAME: backend
      IMAGE_TAG: latest
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      
      - name: Debug AWS Identity
        run: aws sts get-caller-identity
      
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${REPO_URL}

      - name: Build Image
        working-directory: backend
        env:
          IMAGE_TAG: latest
          REPO_NAME: backend
        run: |
          docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag ${REPO_URL}/${IMAGE_NAME}:${IMAGE_TAG} .
        
      - name: Deploy Image
        env:
          IMAGE_TAG: latest
          REPO_NAME: backend
        run: |
            docker push ${REPO_URL}/${IMAGE_NAME}:${IMAGE_TAG}