name: Master CI Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
