name: Master CI Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  frontendCI:
    uses: ./.github/workflows/frontend-ci.yml
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  frontendCD:
    uses: ./.github/workflows/frontend-cd.yml
    needs: frontendCI
    secrets:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}